/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GSDOG */

#ifndef _Included_GSDOG
#define _Included_GSDOG
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GSDOG
 * Method:    DogCheck
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fleety_server_GSDOG_DogCheck
  (JNIEnv *, jobject);

/*
 * Class:     GSDOG
 * Method:    DogConvert
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fleety_server_GSDOG_DogConvert
  (JNIEnv *, jobject);

/*
 * Class:     GSDOG
 * Method:    WriteDog
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fleety_server_GSDOG_WriteDog
  (JNIEnv *, jobject);

/*
 * Class:     GSDOG
 * Method:    ReadDog
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fleety_server_GSDOG_ReadDog
  (JNIEnv *, jobject);


/*
 * Class:     GSDOG
 * Method:    GetCurrentNo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fleety_server_GSDOG_GetCurrentNo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
