// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package server.remote_execute_by_rmi.server;

public final class ClsRemoteRmiInterface_Stub
    extends java.rmi.server.RemoteStub
    implements server.remote_execute_by_rmi.server.IClsRemote, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_clearGroupClass_0;
    private static java.lang.reflect.Method $method_execute_1;
    private static java.lang.reflect.Method $method_registerClass_2;
    
    static {
	try {
	    $method_clearGroupClass_0 = server.remote_execute_by_rmi.server.IClsRemote.class.getMethod("clearGroupClass", new java.lang.Class[] {java.lang.String.class});
	    $method_execute_1 = server.remote_execute_by_rmi.server.IClsRemote.class.getMethod("execute", new java.lang.Class[] {java.lang.String.class, java.lang.String.class, com.fleety.base.InfoContainer.class});
	    $method_registerClass_2 = server.remote_execute_by_rmi.server.IClsRemote.class.getMethod("registerClass", new java.lang.Class[] {java.lang.String.class, java.lang.String.class, byte[].class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public ClsRemoteRmiInterface_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of clearGroupClass(String)
    public void clearGroupClass(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_clearGroupClass_0, new java.lang.Object[] {$param_String_1}, -6993331356418799065L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of execute(String, String, InfoContainer)
    public java.lang.Object execute(java.lang.String $param_String_1, java.lang.String $param_String_2, com.fleety.base.InfoContainer $param_InfoContainer_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_execute_1, new java.lang.Object[] {$param_String_1, $param_String_2, $param_InfoContainer_3}, -1451651709768865072L);
	    return ((java.lang.Object) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of registerClass(String, String, byte[])
    public boolean registerClass(java.lang.String $param_String_1, java.lang.String $param_String_2, byte[] $param_arrayOf_byte_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_registerClass_2, new java.lang.Object[] {$param_String_1, $param_String_2, $param_arrayOf_byte_3}, 161662799978872758L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
