/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fleety_base_GPSEncode */

#ifndef _Included_com_fleety_base_GPSEncode
#define _Included_com_fleety_base_GPSEncode

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fleety_base_GPSEncode
 * Method:    encode
 * Signature: (DD[D)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fleety_base_GPSEncode_encode
  (JNIEnv *, jclass, jdouble, jdouble, jdoubleArray);

/*
 * Class:     com_fleety_base_GPSDecode
 * Method:    decode
 * Signature: (DD[D)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fleety_base_GPSEncode_decode
  (JNIEnv *, jclass, jdouble, jdouble, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
