/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nothome_mswindows_IECanvas */

#ifndef _Included_nothome_mswindows_IECanvas
#define _Included_nothome_mswindows_IECanvas
#ifdef __cplusplus
extern "C" {
#endif
#undef nothome_mswindows_IECanvas_FOCUS_TRAVERSABLE_UNKNOWN
#define nothome_mswindows_IECanvas_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef nothome_mswindows_IECanvas_FOCUS_TRAVERSABLE_DEFAULT
#define nothome_mswindows_IECanvas_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef nothome_mswindows_IECanvas_FOCUS_TRAVERSABLE_SET
#define nothome_mswindows_IECanvas_FOCUS_TRAVERSABLE_SET 2L
/* Inaccessible static: focusTraversalKeyPropertyNames */
/* Inaccessible static: LOCK */
/* Inaccessible static: dbg */
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef nothome_mswindows_IECanvas_TOP_ALIGNMENT
#define nothome_mswindows_IECanvas_TOP_ALIGNMENT 0.0f
#undef nothome_mswindows_IECanvas_CENTER_ALIGNMENT
#define nothome_mswindows_IECanvas_CENTER_ALIGNMENT 0.5f
#undef nothome_mswindows_IECanvas_BOTTOM_ALIGNMENT
#define nothome_mswindows_IECanvas_BOTTOM_ALIGNMENT 1.0f
#undef nothome_mswindows_IECanvas_LEFT_ALIGNMENT
#define nothome_mswindows_IECanvas_LEFT_ALIGNMENT 0.0f
#undef nothome_mswindows_IECanvas_RIGHT_ALIGNMENT
#define nothome_mswindows_IECanvas_RIGHT_ALIGNMENT 1.0f
#undef nothome_mswindows_IECanvas_serialVersionUID
#define nothome_mswindows_IECanvas_serialVersionUID -7644114512714619750i64
/* Inaccessible static: metrics */
/* Inaccessible static: class_00024java_00024awt_00024Component */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ComponentListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024FocusListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyBoundsListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024KeyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseMotionListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseWheelListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024InputMethodListener */
/* Inaccessible static: class_00024java_00024beans_00024PropertyChangeListener */
/* Inaccessible static: nameCounter */
#undef nothome_mswindows_IECanvas_serialVersionUID
#define nothome_mswindows_IECanvas_serialVersionUID -2284879212465893870i64
/*
 * Class:     nothome_mswindows_IECanvas
 * Method:    initialize
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_nothome_mswindows_IECanvas_initialize
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     nothome_mswindows_IECanvas
 * Method:    sendurl
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nothome_mswindows_IECanvas_sendurl
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nothome_mswindows_IECanvas
 * Method:    resizeControl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nothome_mswindows_IECanvas_resizeControl
  (JNIEnv *, jobject);

/*
 * Class:     nothome_mswindows_IECanvas
 * Method:    gohome
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nothome_mswindows_IECanvas_gohome
  (JNIEnv *, jobject);

/*
 * Class:     nothome_mswindows_IECanvas
 * Method:    rld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nothome_mswindows_IECanvas_rld
  (JNIEnv *, jobject);

/*
 * Class:     nothome_mswindows_IECanvas
 * Method:    gofwd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nothome_mswindows_IECanvas_gofwd
  (JNIEnv *, jobject);

/*
 * Class:     nothome_mswindows_IECanvas
 * Method:    gobackwd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nothome_mswindows_IECanvas_gobackwd
  (JNIEnv *, jobject);

/*
 * Class:     nothome_mswindows_IECanvas
 * Method:    setfocus
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nothome_mswindows_IECanvas_setfocus
  (JNIEnv *, jobject);

/*
 * Class:     nothome_mswindows_IECanvas
 * Method:    setInnerHtml
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nothome_mswindows_IECanvas_setInnerHtml
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     nothome_mswindows_IECanvas
 * Method:    getInnerHtml
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nothome_mswindows_IECanvas_getInnerHtml
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nothome_mswindows_IECanvas
 * Method:    setClassName
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nothome_mswindows_IECanvas_setClassName
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     nothome_mswindows_IECanvas
 * Method:    getClassName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nothome_mswindows_IECanvas_getClassName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nothome_mswindows_IECanvas
 * Method:    executeJavascript
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nothome_mswindows_IECanvas_executeJavascript
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
